### ISSUE TITLE
Gesture Handler does not work on Chrome based web views

### ISSUE THREAD

**Issue by cakuki** [dashersw/erste#17]
Gesture handler cannot proceed after an error is thrown when it tries to modify `target` property of Touch events.

Got this error on  Android 6.0.1, Chrome 56.0.2924.87

```
Uncaught TypeError: Cannot assign to read only property 'target' of object '#<Event>'
    at GestureHandler$$module$node_modules$erste$src$lib$base$gesture_handler.onTouchend
```

**Comment by dashersw** [comment]
Hm, I'm pretty sure this is something new... I remember reading about this.

**Comment by dashersw** [comment]
Actually, in one of the last commits I had moved on to using `target` from another custom property. Apparently this was why we were using a custom property before.
