### ISSUE TITLE
TabView do not work

### ISSUE THREAD

**Issue by csonmez** [dashersw/erste#36]
TabView do not work from v4.1.3. 

When upgrade erste version in erste-demo, tab-view get error.
Error: **Uncaught TypeError: Array.prototype.indexOf called on null or undefined** in tab-view.js:52

**Comment by dashersw** [comment]
Thank you for the report! I will be looking into this shortly!

**Comment by dashersw** [comment]
Hi! I just released erste@4.6.3 — could you try that version? It's supposed to solve this issue.

**Comment by csonmez** [comment]
Hi! Yes, it's working now. Thank you.
