### ISSUE TITLE
May remove documentation from in the repository

### ISSUE THREAD

**Issue by abdullah** [dashersw/erste#5]
This issue may result in mess, like this [#9079](https://github.com/facebook/react/issues/9079)

**Comment by dashersw** [comment]
Yes! Actually, it's never my intention to keep tons of documentation within the repo. We'll just have the readme, and a separate wiki or github pages for extended documentation.

**Comment by anonrig** [comment]
What about adding README and similar documents to `.npmignore`?

**Comment by abdullah** [comment]
@anonrig This solution should be valid while repository is getting bigger. I think documentation is always useful outside the repository and therefore each documentation must have  a website.

**Comment by dashersw** [comment]
@anonrig definitely. But still, when you clone the repo for inspection, further development, customization, etc, it gives you everything. Which may not be what you want.

**Comment by anonrig** [comment]
On the contrary, as a developer being able to access the documentation from the same repo *might* be a good thing. @dashersw

**Comment by abdullah** [comment]
Very few people look in the folder for documantation

**Comment by dashersw** [comment]
@anonrig it might. I don't have a strong opinion on this.
